### ISSUE TITLE
Turn stop

### ISSUE THREAD

**Issue by toguspyder** [gnivler/PanicSystem#39]
First, I love the concept of the mod and how it works, so please keep up the great job.

Now the problem: when an enemy ejects (normally last mech on board) the game does not advance to last turn for combat final. I think this glitch may be connected to the eject problem over all. Is there a way of having the enemy eject on there round and not when attacked?
Also, if they are going to eject, have them stand the mech first and/or run away before ejecting (this seems to be one of the work arounds for the eject problem).

Here are a couple of threads that relate to the eject bug:
https://steamcommunity.com/app/637090/discussions/0/1693795812287632730/
https://steamcommunity.com/app/637090/discussions/0/1696048426817029570/

Looking forward to seeing more on this.

**Comment by gnivler** [comment]
Thanks for the feedback, we're glad you like it.

There was a time when this was an issue but it hasn't recurred to my
knowledge, in quite some time.  I will need the output_log.txt or at least
the exceptions being thrown in it, and if you have turn on debug in the
mod.json and include that it couldn't hurt.

Also make sure your DLL version 3.04, which I assume is the case since
you're posting to github, but since what you're describing seems like old
bug it needs to be covered off.  Those threads definitely predate the
bugfixes for ejection FWIW, I didn't even start coding on PanicSystem until
June and the hang fixes were not complete until the very last release Aug
28th.

**Comment by toguspyder** [comment]
Thanks for the quick feedback. I am currently running the latest version of all the mods to it and recommended to it. I’ll have a log for you some time later today (as soon as I know I’m doing it right).

**Comment by toguspyder** [comment]
Here is the info from the log file:

12:23:15 PM PanicSystem v3.0.4
New contract; done reset
##############################################
Phoenix Hawk attacks Jenner
Damage >>> Armor: 22.5 Structure: 0 (3.68%)
Not enough damage
##############################################
Cicada attacks Jenner
Damage >>> Armor: 12.5 Structure: 0 (2.12%)
Not enough damage
Condition worsened: Unsetlled
Condition worsened: Stressed
##############################################
Centurion attacks Cicada
Damage >>> Armor: 103 Structure: 80 (27.9%)
Structure damage requires panic save
----------------------------------------------
Factors              |     Change |      Total
----------------------------------------------
Mech health 72.1%    |            |
Pilot injuries       |     16.667 |     16.667
CT                   |     26.207 |     42.874
LT                   |         25 |     67.874
Guts and Tactics     |         -9 |     58.874
Resolve 29           |       -1.6 |     57.274
Panic multiplier     |       0.66 |     37.801
----------------------------------------------
Saving throw         | 38      51 |       Roll
----------------------------------------------
Successful panic save
##############################################
Griffin attacks Cicada
Damage >>> Armor: 62 Structure: 33 (20.08%)
Structure damage requires panic save
----------------------------------------------
Factors              |     Change |      Total
----------------------------------------------
Mech health 57.62%   |            |
Pilot injuries       |     16.667 |     16.667
CT                   |     57.241 |     73.908
LT                   |         25 |     98.908
RL                   |      4.688 |    103.596
Guts and Tactics     |         -9 |     94.596
Resolve 29           |       -1.6 |     92.996
Panic multiplier     |       0.66 |     61.377
----------------------------------------------
Saving throw         | 61      71 |       Roll
----------------------------------------------
Successful panic save
##############################################
Griffin attacks Phoenix Hawk
Damage >>> Armor: 16 Structure: 0 (1.41%)
Not enough damage
##############################################
Shadow Hawk attacks Cicada
Damage >>> Armor: 4 Structure: 25 (7.67%)
Structure damage requires panic save
----------------------------------------------
Factors              |     Change |      Total
----------------------------------------------
Mech health 53.2%    |            |
Pilot injuries       |     16.667 |     16.667
CT                   |     74.483 |     91.149
LT                   |         25 |    116.149
RL                   |      5.438 |    121.587
Guts and Tactics     |         -9 |    112.587
Resolve 29           |       -1.6 |    110.987
Panic multiplier     |       0.66 |     73.251
----------------------------------------------
Saving throw         | 73      16 |       Roll
----------------------------------------------
Failed panic save
Condition worsened: Panicked
Base ejection resist |         75 |     35.987
Eject multiplier     |          1 |         36
----------------------------------------------
Saving throw         | 36      75 |       Roll
----------------------------------------------
Successful ejection save
##############################################
Phoenix Hawk attacks Centurion
Damage >>> Armor: 70 Structure: 0 (5.4%)
Not enough damage
##############################################
Vindicator attacks Centurion
Damage >>> Armor: 4 Structure: 0 (.33%)
Not enough damage
##############################################
Centurion attacks Phoenix Hawk
Damage >>> Armor: 106 Structure: 30 (12.14%)
Structure damage requires panic save
----------------------------------------------
Factors              |     Change |      Total
----------------------------------------------
Mech health 86.62%   |            |
CT                   |       6.19 |       6.19
LT                   |       1.97 |       8.16
LL                   |       .818 |      8.978
RL                   |       .364 |      9.342
Guts and Tactics     |        -18 |     -8.658
Resolve 40           |         -6 |    -14.658
Panic multiplier     |          1 |    -14.658
Negative saving throw; skipping
##############################################
Griffin attacks Cicada
Damage >>> Armor: 18.75 Structure: 0 (5.37%)
Not enough damage
##############################################
Griffin attacks Phoenix Hawk
Damage >>> Armor: 4 Structure: 4 (.81%)
Not enough damage
##############################################
Shadow Hawk attacks Phoenix Hawk
Damage >>> Armor: 69 Structure: 0 (7.07%)
Not enough damage
Condition improved: Stressed
##############################################
Phoenix Hawk attacks Centurion
Damage >>> Armor: 25 Structure: 0 (2.05%)
Not enough damage
##############################################
Vindicator attacks Griffin
Damage >>> Armor: 67 Structure: 0 (5.51%)
Not enough damage
##############################################
Cicada attacks Griffin
Damage >>> Armor: 25 Structure: 0 (2.18%)
Not enough damage
Condition worsened: Panicked
##############################################
Griffin attacks Cicada
Damage >>> Armor: 12.25 Structure: 57.75 (21.2%)
Structure damage requires panic save
----------------------------------------------
Factors              |     Change |      Total
----------------------------------------------
Mech health 39.67%   |            |
Pilot injuries       |     16.667 |     16.667
Knockdown            |          5 |     21.667
CT                   |     74.483 |     96.149
LT                   |         25 |    121.149
RT                   |      9.934 |    131.084
RL                   |         15 |    146.084
Guts and Tactics     |         -9 |    137.084
Resolve 57           |      -12.8 |    124.284
Panic multiplier     |        0.5 |     62.142
----------------------------------------------
Saving throw         | 62      89 |       Roll
----------------------------------------------
Successful panic save
##############################################
Centurion attacks Phoenix Hawk
Damage >>> Armor: 108 Structure: 28 (14.99%)
Structure damage requires panic save
----------------------------------------------
Factors              |     Change |      Total
----------------------------------------------
Mech health 67.87%   |            |
CT                   |     31.429 |     31.429
LT                   |      3.788 |     35.216
RT                   |     17.879 |     53.095
LL                   |       .818 |     53.913
RL                   |       .364 |     54.277
Guts and Tactics     |        -18 |     36.277
Resolve 12           |        5.2 |     41.477
Panic multiplier     |          1 |     41.477
----------------------------------------------
Saving throw         | 41      41 |       Roll
----------------------------------------------
Successful panic save
Condition worsened: Unsetlled
Condition worsened: Stressed
##############################################
Shadow Hawk attacks Phoenix Hawk
Damage >>> Armor: 108 Structure: 72 (23.35%)
Structure damage requires panic save
----------------------------------------------
Factors              |     Change |      Total
----------------------------------------------
Mech health 52.02%   |            |
Pilot injuries       |      18.75 |      18.75
Unsteady             |          5 |      23.75
CT                   |     59.524 |     83.274
LT                   |      3.788 |     87.062
RT                   |         25 |    112.062
LL                   |       .818 |     112.88
RL                   |      1.091 |    113.971
Guts and Tactics     |        -18 |     95.971
Resolve 16           |        3.6 |     99.571
Panic multiplier     |       0.66 |     65.717
----------------------------------------------
Saving throw         | 66      49 |       Roll
----------------------------------------------
Failed panic save
Condition worsened: Panicked
Base ejection resist |         75 |     24.571
Eject multiplier     |          1 |         25
----------------------------------------------
Saving throw         | 25      84 |       Roll
----------------------------------------------
Successful ejection save
##############################################
Vindicator attacks Centurion
Damage >>> Armor: 55 Structure: 0 (4.59%)
Not enough damage
##############################################
Phoenix Hawk attacks Centurion
Damage >>> Armor: 55 Structure: 0 (5.06%)
Not enough damage
##############################################
Phoenix Hawk attacks Centurion
No damage
##############################################
Cicada attacks Griffin
No damage

It doesn't show the attack.

**Comment by gnivler** [comment]
The output_log.txt is the one I need to see most, it will show what
exceptions are thrown.  Both together is the full picture if you can.
Thanks
