### ISSUE TITLE
version 3.3 hangs when pilot ejects

### ISSUE THREAD

**Issue by Ruffyen** [gnivler/PanicSystem#43]
I installed and tried "PanicSystem" but on the first enemy I forced to eject my game froze as he yelled "My...My mech!!!" I could not select anything only esc to leave the mission. In any case I have run 9 successful missions after removing the mod so not sure if it's the cause but maybe you can check?

I am currently running the following mods with 1.6.. (non-Urban)
- **MechEngineer** by CptMoore (w/CustomComponents included)
- **CBTMovementCore** by Joe Guetler, Madranis ["Version": "v0.5.2"]
- **LootMagnet** by IceRaptor ["Version": "2.5.1"]
- **CrystalClear** by Gnivler
- **CustomSalvage** by Denadan
- **AddYearToTimeline** by Zathoth
- **AmmoCookOff** by RealityMachina
- **ModTek** by MpStark [v0.7.2]
- **MoveFaster** by Willssi [v0.1] (to speed up missiles and stuff to make the turns go faster)
- **PermanentEvasion** ["Version": "v1.1.6.2"] by Redferne (original by Morphyum)
- **PilotHealthPopup** by MpStark ["Version": "1.6.0"]
- **RepairBays** by raok ["Version": "0.1.0.2"] (I think this is fixed version for Roguetech?)
- **SkipIntro** by MpStark ["Version": "1.6.0"]
- **SkipTravelCutscenes** by MpStark ["Version": "1.6.0"]
- **CustomAmmoCategories** ["Version": "0.1.9"] by KMiSSioN (with WeaponRealizer - janxious, and AttackImprovementMod - Sheepy included)

Also here is the last part of my "output_log.txt" file (in case it helps)..
> [DEBUG] Floatie PILOT EJECTED

(Filename: C:/dev/5.6.6f2/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

MessageCenter [ERROR] CRITICAL ERROR, PLEASE REPORT:
Delegate OnAttackComplete - Standard for message type OnAttackComplete failed with exception
Method not found: 'BattleTech.WeaponHitInfo..ctor'.
at (wrapper dynamic-method) BattleTech.Mech.CheckForHeatDamage_Patch2 (object,int,string) <0x00b35>
at BattleTech.Mech.ReconcileHeat (int,string) <0x00029>
at BattleTech.Mech.AdjustHeatDirectly (single,int,string) <0x00159>
at BattleTech.Mech.HandleDeath (string) <0x001b1>
at BattleTech.AbstractActor.EjectPilot (string,int,BattleTech.DeathMethod,bool) <0x00136>
at BattleTech.Mech.EjectPilot (string,int,BattleTech.DeathMethod,bool) <0x0008b>
at PanicSystem.Patches/AttackStackSequenceOnAttackCompletePatch.Prefix (BattleTech.AttackStackSequence,MessageCenterMessage) <0x00a8c>
at (wrapper dynamic-method) BattleTech.AttackStackSequence.OnAttackComplete_Patch1 (object,MessageCenterMessage) <0x00029>
at MessageCenter.SendMessagesForType (MessageCenterMessageType,MessageCenterMessage) <0x00186>

(Filename: C:/dev/5.6.6f2/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

MechEngineer [DEBUG] Floatie Panicked

(Filename: C:/dev/5.6.6f2/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

MechEngineer [DEBUG] Floatie Punching out!

(Filename: C:/dev/5.6.6f2/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Could not find num flag for combatant Jenner

(Filename: C:/dev/5.6.6f2/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Could not find num flag for combatant Wolverine

(Filename: C:/dev/5.6.6f2/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by Ruffyen** [comment]
I got some help from KMiSSioN and the problem was AmmoCookOff by RealityMachina.
After removing that mod, the Panic System mod worked with Battletech 1.6 update.

You can close this issue.

Thank you!

**Comment by gnivler** [comment]
Great, glad you figure it out and thanks for the detailed report in any event.
