### ISSUE TITLE
panic descriptions vague

### ISSUE THREAD

**Issue by deadlyshelter** [gnivler/PanicSystem#45]
i love your mod but i find the names chosen for panic status are a little vague.  something on the order of and in order of personal taste, and yes it is somewhat a matter of taste

**assured** for _confident_
**shaken**, alarmed, worried, or concerned for _unsettled_
**frightened**, nervous, scared, or stunned for _stressed_
**dismayed**, terrified, mortified, horrified for _panicked_

**Comment by gnivler** [comment]
Thanks for the feedback, it will taken under advisement.
