### ISSUE TITLE
Pilot gets unexpected Confident state

### ISSUE THREAD

**Issue by WachoTheClown** [gnivler/PanicSystem#54]
[4-29 output_log.txt](https://github.com/gnivler/PanicSystem/files/4554424/4-29.output_log.txt)
Is this project still under active development?
I am seeing messages about pilots becoming confident, round before they are killed as the last man standing, or one of only two.

Strangely this is the only log immediately before the pilot gets the "confident" tag

2020-04-29T13:15:36 FYLS [LOG] Hollander loses effect Unsettled due to cancellation or removal

I think this behavior isn't the expected one.

**Comment by gnivler** [comment]
Sorry I am not in a position to help

**Comment by gnivler** [comment]
The project is still being worked on by folks in the Discord community yeah.  I'm technically still maintaining the repo, there is also this fork https://github.com/BattletechModders/PanicSystem.

Troubleshooting this would require effort I'm not willing/able to put forth in the foreseeable future sorry, but others are seeing this issue.  You could also hit up the RT Discord.

**Comment by fmnatic** [comment]
Tracked this down, it happens if the mech hasn't been damaged in a few turns, at the start of a new round, irrespective of the state of the mech/mission. Fix is in the works.
