### ISSUE TITLE
Hardened mechs experience extreme panic effects

### ISSUE THREAD

**Issue by LokiAz9** [gnivler/PanicSystem#56]
I have a Hunchback 50t and Mauler 90t both with Hardened armor.  When they take the slightest damage, they start to get panicked.  I reloaded a few times at first when my pilot ejected after taking virtually no damage.

It looks like the problem is with the Helper functions.  The armor max values are probably wrong with Hardened.

        internal static float PercentCenterTorso(Mech mech) =>
            (mech.CenterTorsoStructure +
             mech.CenterTorsoFrontArmor +
             mech.CenterTorsoRearArmor) /
            (mech.MaxStructureForLocation((int) ChassisLocations.CenterTorso) +
             mech.MaxArmorForLocation((int) ArmorLocation.CenterTorso) +
             mech.MaxArmorForLocation((int) ArmorLocation.CenterTorsoRear));

See #rogueticket-382 on discord for more discussion.

Here's a screenshot of my mech panicking near two nearly dead enemy mechs.  I've learned to disengage at this point to keep them from ejecting for no reason.

![20200519130108_1](https://user-images.githubusercontent.com/65670503/83355002-702d2600-a311-11ea-970f-2f0e8c8f2d0d.jpg)

**Comment by gnivler** [comment]
PR #57
